### ISSUE TITLE
[FIX] QA 반영

### ISSUE THREAD

**Issue by lhb8106** [Team-InIT/inIT_AOS#141]
## 🌻 Issue
QA 반영

## 📑 To-do
- [x] 프로젝트 파트별 자격요건
- [x] 스택 없을 시, 텍스트 안 뜨게
- [x] chip group 완료 버튼 눌렀을 시, textfield 비워지게
- [x] chip group 서버통신 전 초기화
- [x] pNum, mNum, fNum 수정
