### ISSUE TITLE
[FEAT] 미평가 팀원 로직 생성

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#150]
## 🌻 Issue
미평가 팀원 평가 리사이클러뷰 생성

## 📑 To-do
- [x] 리사이클러뷰 생성
- [x] 뷰모델 생성
- [x] 클릭 이벤트 생성
- [x] 추천 selector 이벤트 생성
- [x] 평가 후 완료 알럿 생성하기
