### ISSUE TITLE
[FEAT] 평가 완료 팀원 리스트 서버 통신

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#173]
## 🌻 Issue
평가 완료 팀원 리스트 서버 통신

## 📑 To-do
- [x] 평가완료 팀원 리스트 조회
- [x] 평가 내용 조회
- [x] 평가 삭제 서버통신
