### ISSUE TITLE
[FEAT] 회원가입 서버통신

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#196]
## 🌻 Issue
회원가입 서버 통신을 진행합니다.

## 📑 To-do
- [ ] 일반_회원가입 연결
- [ ] 기업_회원가입 연결
- [ ] request 데이터 타입 변경
