### ISSUE TITLE
[MODIFY] 바텀네비 수정

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#30]
## 🌻 Issue
바텀네비 디자인을 수정합니다

## 📑 To-do
- [x] 피드 아이콘 넣기
- [x] 바텀 네비 xml 수정
- [x] 바텀 네비 코드 수정
