### ISSUE TITLE
[UI] 홈 뷰 레이아웃

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#33]
## 🌻 Issue
홈 화면의 뷰를 완성합니다.

## 📑 To-do
- [x] 기본 홈 화면 만들기
- [x] 프로젝트 리사이클러뷰 아이템 만들기 
- [x] 상단의 뷰페이저 만들기
- [x] 데이터가 없을 경우의 화면 만들기
