### ISSUE TITLE
[UI] 검색화면 뷰 완성

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#39]
## 🌻 Issue
검색화면 뷰 완성

## 📑 To-do
- [x] 이미지 및 아이콘 넣기
- [x] 탭 세 개 만들기
- [x] 모집 중 탭 완성
- [x] 모집 완료 탭 완성
- [x] 파트너 탭 완성
- [x] 검색 요소 선택 다이얼로그 만들기
