### ISSUE TITLE
[FEAT] 로그인/회원가입 기능 구현

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/inIT_AOS#6]
## 🌻 Issue
서버 연결 전까지의 기능을 구현합니다.

## 📑 To-do
- [x] 회원가입 프로그래스 바 이동확인
- [x] 기본화면 recyclerview 생성
- [x] edittext 유효성 검사하기
- [x] Fragment 간의 이동 확인
