### ISSUE TITLE
[MODIFY] 마이페이지 수정

### ISSUE THREAD

**Issue by lhb8106** [Team-InIT/inIT_AOS#97]
## 🌻 Issue
마이페이지 로직을 수정합니다

## 📑 To-do
- [x] 빠진 뷰 확인 및 수정
- [x] 타인마이페이지, 내 마이페이지 분기처리
- [x] adapter 버그 수정
